version: "2"
services:

  web:
    build:
      context: .
      dockerfile: container-build/web/DockerFile
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=intranet
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_HOST=db
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on:
      - db
  db:
    image: mysql:5.7
    ports:
      - "6603:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=intranet
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123
      - MYSQL_HOST=db

volumes:
  mysql_data: { driver: local}
